### PR TITLE
fix hostfile hybridmap reuse

### LINKED ISSUE #236: Use `recover()` to catch runtime panics
### Proposed Changes

- `net/http` has recover statement with defer in every goroutine it creates to catch panics
-  while running nuclei scan on 250 targets , it paniced after 3hrs 45 min 

```
[3:44:50] | Templates: 7384 | Hosts: 253 | RPS: 141 | Matched: 3255 | Errors: 50463 | Requests: 1911514/2797674 (68%)
panic: runtime error: slice bounds out of range [1721:49]

goroutine 26744483 [running]:
internal/poll.(*FD).Write(0x14016273600, {0x1403009ce00, 0x31, 0x32})
	internal/poll/fd_unix.go:380 +0x3ac
net.(*netFD).Write(0x14016273600, {0x1403009ce00?, 0x104f0f0e0?, 0x10512e220?})
	net/fd_posix.go:96 +0x28
net.(*conn).Write(0x14011ed7d48, {0x1403009ce00?, 0x14042d90fd8?, 0x10289b44c?})
	net/net.go:191 +0x34
github.com/miekg/dns.(*Conn).Write(0x1400dce5400, {0x1403009ce00, 0x31, 0x32})
	github.com/miekg/dns@v1.1.57/client.go:359 +0x108
github.com/miekg/dns.(*Conn).WriteMsg(0x1400dce5400, 0xc47f431c4ed?)
	github.com/miekg/dns@v1.1.57/client.go:348 +0xe4
github.com/miekg/dns.(*Client).ExchangeWithConnContext(0x140009faa80, {0x1051e4b78, 0x106722380}, 0x14015f11440, 0x1400dce5400)
	github.com/miekg/dns@v1.1.57/client.go:220 +0x2a8
github.com/miekg/dns.(*Client).ExchangeWithConn(...)
	github.com/miekg/dns@v1.1.57/client.go:187
github.com/miekg/dns.(*Client).Exchange(0x140451584e0?, 0x140451584e0?, {0x14013099540?, 0x104a08320?})
	github.com/miekg/dns@v1.1.57/client.go:170 +0xe0
github.com/projectdiscovery/retryabledns.(*Client).queryMultiple(0x14000b6d5f0, {0x140451584e0, 0x14}, {0x14042d913c4, 0x2, 0x1031545f0?}, {0x0, 0x0})
	github.com/projectdiscovery/retryabledns@v1.0.50/client.go:361 +0x718
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(...)
	github.com/projectdiscovery/retryabledns@v1.0.50/client.go:264
github.com/projectdiscovery/retryabledns.(*Client).Resolve(0x1400039c6c0?, {0x140451584e0?, 0x140451584e0?})
	github.com/projectdiscovery/retryabledns@v1.0.50/client.go:144 +0x44
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).GetDNSData(0x1400039c6c0, {0x140451584e0?, 0x1051c1700?})
	github.com/projectdiscovery/fastdialer@v0.0.52/fastdialer/dialer.go:489 +0x390
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).dial(0x1400039c6c0, {0x1051e4da8, 0x14003ed2e00}, {0x103fcdf09, 0x3}, {0x140451584e0, 0x17}, 0x0, 0x0, 0x0, ...)
	github.com/projectdiscovery/fastdialer@v0.0.52/fastdialer/dialer.go:216 +0x29c
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).Dial(...)
	github.com/projectdiscovery/fastdialer@v0.0.52/fastdialer/dialer.go:136
github.com/projectdiscovery/retryablehttp-go.DefaultReusePooledTransport.func1({0x1051e4da8?, 0x14003ed2e00?}, {0x103fcdf09?, 0x104d9dfe0?}, {0x140451584e0?, 0x1027f249c?})
	github.com/projectdiscovery/retryablehttp-go@v1.0.42/http.go:52 +0x64
net/http.(*Transport).dial(0x1400f4bb5c0?, {0x1051e4da8?, 0x14003ed2e00?}, {0x103fcdf09?, 0x14042d91a58?}, {0x140451584e0?, 0x1?})
	net/http/transport.go:1183 +0xdc
net/http.(*Transport).dialConn(0x14000c39180, {0x1051e4da8, 0x14003ed2e00}, {{}, 0x0, {0x14008fad780, 0x4}, {0x140451584e0, 0x17}, 0x0})
	net/http/transport.go:1625 +0x61c
net/http.(*Transport).dialConnFor(0x140253bf260?, 0x1401def9550)
	net/http/transport.go:1467 +0x7c
created by net/http.(*Transport).queueForDial in goroutine 26738384
	net/http/transport.go:1436 +0x380
```

this seems mostly due to open fd etc but i think maybe panic could have been avoided if we have added recover and caught it in fastdialer

### LINKED ISSUE #248: fix nil hostfile data during reuse
### Proposed Changes

- due to incorrect referencing of variable (global -> local) . consequent calls to loadhostFile were returning nil data

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
### Proposed Changes

- during lazy initialization hm updated local variable instead global variable 
- which caused subsequent calls to return nil  instance with no /etc/hosts data
- closes #236 
- closes #248

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
### example

- add entry to /etc/hosts
```

## testing

127.0.0.1  nuclei.test

```

```console
$ ./nuclei -u nuclei.test:8000 -id tech-detect -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.7

		projectdiscovery.io

[INF] Current nuclei version: v3.1.7 (latest)
[INF] Current nuclei-templates version: v9.7.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 6
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] [tech-detect] Dumped HTTP request for http://nuclei.test:8000

GET / HTTP/1.1
Host: nuclei.test:8000
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[DBG] [tech-detect] Dumped HTTP response http://nuclei.test:8000

HTTP/1.1 200 OK
Connection: close
Content-Length: 13
Content-Type: text/html; charset=utf-8
Date: Thu, 25 Jan 2024 16:23:25 GMT
Last-Modified: Thu, 25 Jan 2024 16:18:31 GMT

<pre>
</pre>
[INF] No results found. Better luck next time!

```

File: fastdialer/dialer.go [hunk 1]
```diff
@@ -127,10 +127,14 @@ func NewDialer(options Options) (*Dialer, error) {
 	var hostsFileData *hybrid.HybridMap
 	// load hardcoded values from host file
 	if options.HostsFile {
+		var err error
```
Comment (Mzack9999) [inline fastdialer/dialer.go:130]: I think hosts file loading should mimic the default OS behavior: if for any reason the hosts file is not accessible the system performs the DNS lookup with the specific query. What do you think of eventually accepting an optional logger similarly to `net/http`

**Review by Mzack9999 — APPROVED** [review]
lgtm - left an optional note related to failure behavior

**Review by Mzack9999 — APPROVED** [review]
